import createConnection from '../index'

async function create() {
  const connection = await createConnection()

  await connection.query(`truncate migrations`)
  await connection.query(`drop table users`)
  await connection.query(`drop table block_reasons`)
  await connection.query(`drop table user_groups`)
  await connection.query(`drop table negociacao`)
  await connection.query(`drop table medicao`)
  await connection.query(`drop table cadastro_obra`)
  await connection.query(`drop table pacotes_items`)
  await connection.query(`drop table pacotes`)
  await connection.query(`drop table pedidos_items`)
  await connection.query(`drop table pedidos`)
  await connection.query(`drop table status_negociacao`)
  await connection.query(`drop table altura_vaos`)
  await connection.query(`drop table largura_vaos`)
  await connection.query(`drop table alizar`)
  await connection.query(`drop table fechadura`)
  await connection.query(`drop table tipo_porta`)
  await connection.query(`drop table sentido_abertura`)
  await connection.query(`drop table tipo_enchimento`)
  await connection.query(`drop table padrao_cor`)
  await connection.query(`drop table clientes`)
  await connection.query(`drop table funcionarios`)
  await connection.query(`drop table ceps`)
  await connection.query(`drop table cidades`)
  await connection.query(`drop table estados`)
  await connection.query(`drop table paises`)
  await connection.query(`drop table user_tokens`)
  await connection.query(`drop table menu_options`)
  await connection.query(`drop table modules`)
  await connection.query(`drop table navigation`)
  await connection.query(`drop table profile_options`)
  await connection.query(`drop table users_profiles`)
  await connection.query(`drop table profiles`)
  await connection.query(`drop table users`)
  await connection.query(`drop table block_reasons`)
  await connection.query(`drop table user_groups`)

  await connection.close()
}

create().then(() => console.log('Tabelas deletadas!'))
